export const GET_NOTE_LIST_REQUEST = "GET_NOTE_LIST_REQUEST";
export const GET_NOTE_LIST_SUCCESS = "GET_NOTE_LIST_SUCCESS";
export const GET_NOTE_LIST_FAILED = "GET_NOTE_LIST_FAILED";
export const GET_NOTE_LIST_LOADING = "GET_NOTE_LIST_LOADING";
